# Generated by Django 6.0.2 on 2026-03-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_prof',
            field=models.ImageField(default='img_en/auth/person-fill.svg', upload_to='img_en/auth/', verbose_name='Фото профиля'),
        ),
    ]
