# Generated by Django 6.0.2 on 2026-03-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_prof',
            field=models.ImageField(blank=True, default='img_en/auth/person-fill.svg', null=True, upload_to='img_en/auth/', verbose_name='Фото профиля'),
        ),
    ]
