# Generated by Django 6.0.2 on 2026-03-19 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customuser_photo_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='kartochka_tovara',
            name='opisanie',
            field=models.CharField(default=0, max_length=600, verbose_name='Описание энергетика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kartochka_tovara',
            name='xar',
            field=models.CharField(default=django.utils.timezone.now, verbose_name='Характеристрики'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kartochka_tovara',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
