# Generated by Django 6.0.2 on 2026-03-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_kartochka_tovara_opisanie_kartochka_tovara_xar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartochka_tovara',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
