# Generated by Django 6.0.2 on 2026-03-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_kartochka_tovara_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kartochka_tovara',
            old_name='id',
            new_name='item_id',
        ),
    ]
