# Generated by Django 6.0.2 on 2026-03-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_id_kartochka_tovara_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kartochka_tovara',
            old_name='item_id',
            new_name='tovar_id',
        ),
    ]
